/*
###############################################################
#  Generated by:      Cadence Innovus 15.23-s045_1
#  OS:                Linux x86_64(Host ID ieng6-ece-02.ucsd.edu)
#  Generated on:      Thu Feb 19 04:39:34 2026
#  Design:            add
#  Command:           saveNetlist add.pnr.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : K-2015.06-SP2
// Date      : Thu Feb 19 04:18:23 2026
/////////////////////////////////////////////////////////////
module csa3_2_5 (
	x, 
	y, 
	z, 
	s, 
	c);
   input x;
   input y;
   input z;
   output s;
   output c;

   FA1D0 U1 (.A(x),
	.B(y),
	.CI(z),
	.CO(c),
	.S(s));
endmodule

module csa2_2_1 (
	x, 
	y, 
	s, 
	c);
   input x;
   input y;
   output s;
   output c;

   CKAN2D0 U1 (.A1(y),
	.A2(x),
	.Z(c));
   IAO21D0 U2 (.A1(y),
	.A2(x),
	.B(c),
	.ZN(s));
endmodule

module csa3_2_0 (
	x, 
	y, 
	z, 
	s, 
	c);
   input x;
   input y;
   input z;
   output s;
   output c;

   FA1D0 U1 (.A(x),
	.B(y),
	.CI(z),
	.CO(c),
	.S(s));
endmodule

module csa3_2_1 (
	x, 
	y, 
	z, 
	s, 
	c);
   input x;
   input y;
   input z;
   output s;
   output c;

   FA1D0 U1 (.A(x),
	.B(y),
	.CI(z),
	.CO(c),
	.S(s));
endmodule

module csa3_2_2 (
	x, 
	y, 
	z, 
	s, 
	c);
   input x;
   input y;
   input z;
   output s;
   output c;

   FA1D0 U1 (.A(x),
	.B(y),
	.CI(z),
	.CO(c),
	.S(s));
endmodule

module csa3_2_3 (
	x, 
	y, 
	z, 
	s, 
	c);
   input x;
   input y;
   input z;
   output s;
   output c;

   FA1D0 U1 (.A(x),
	.B(y),
	.CI(z),
	.CO(c),
	.S(s));
endmodule

module csa3_2_4 (
	x, 
	y, 
	z, 
	s, 
	c);
   input x;
   input y;
   input z;
   output s;
   output c;

   FA1D0 U1 (.A(x),
	.B(y),
	.CI(z),
	.CO(c),
	.S(s));
endmodule

module csa2_2_0 (
	x, 
	y, 
	s, 
	c);
   input x;
   input y;
   output s;
   output c;

   CKAN2D0 U1 (.A1(y),
	.A2(x),
	.Z(c));
   IAO21D0 U2 (.A1(y),
	.A2(x),
	.B(c),
	.ZN(s));
endmodule

module add (
	clk, 
	out, 
	x, 
	y, 
	z);
   input clk;
   output [5:0] out;
   input [3:0] x;
   input [3:0] y;
   input [3:0] z;

   // Internal wires
   wire c0;
   wire s1;
   wire c1;
   wire s2;
   wire c2;
   wire s3;
   wire c3;
   wire c5;
   wire c6;
   wire c7;
   wire [3:0] x_q;
   wire [3:0] y_q;
   wire [3:0] z_q;
   wire [5:0] out_wire;

   csa3_2_5 csa3_2_instance0 (.x(x_q[0]),
	.y(y_q[0]),
	.z(z_q[0]),
	.s(out_wire[0]),
	.c(c0));
   csa3_2_4 csa3_2_instance1 (.x(x_q[1]),
	.y(y_q[1]),
	.z(z_q[1]),
	.s(s1),
	.c(c1));
   csa3_2_3 csa3_2_instance2 (.x(x_q[2]),
	.y(y_q[2]),
	.z(z_q[2]),
	.s(s2),
	.c(c2));
   csa3_2_2 csa3_2_instance3 (.x(x_q[3]),
	.y(y_q[3]),
	.z(z_q[3]),
	.s(s3),
	.c(c3));
   csa2_2_1 csa2_2_instance4 (.x(c0),
	.y(s1),
	.s(out_wire[1]),
	.c(c5));
   csa3_2_1 csa3_2_instance5 (.x(c1),
	.y(s2),
	.z(c5),
	.s(out_wire[2]),
	.c(c6));
   csa3_2_0 csa3_2_instance6 (.x(c2),
	.y(s3),
	.z(c6),
	.s(out_wire[3]),
	.c(c7));
   csa2_2_0 csa2_2_instance7 (.x(c3),
	.y(c7),
	.s(out_wire[4]),
	.c(out_wire[5]));
   DFQD1 z_q_reg_3_ (.CP(clk),
	.D(z[3]),
	.Q(z_q[3]));
   DFQD1 z_q_reg_2_ (.CP(clk),
	.D(z[2]),
	.Q(z_q[2]));
   DFQD1 z_q_reg_1_ (.CP(clk),
	.D(z[1]),
	.Q(z_q[1]));
   DFQD1 z_q_reg_0_ (.CP(clk),
	.D(z[0]),
	.Q(z_q[0]));
   DFQD1 x_q_reg_3_ (.CP(clk),
	.D(x[3]),
	.Q(x_q[3]));
   DFQD1 x_q_reg_2_ (.CP(clk),
	.D(x[2]),
	.Q(x_q[2]));
   DFQD1 x_q_reg_1_ (.CP(clk),
	.D(x[1]),
	.Q(x_q[1]));
   DFQD1 x_q_reg_0_ (.CP(clk),
	.D(x[0]),
	.Q(x_q[0]));
   DFQD1 y_q_reg_3_ (.CP(clk),
	.D(y[3]),
	.Q(y_q[3]));
   DFQD1 y_q_reg_2_ (.CP(clk),
	.D(y[2]),
	.Q(y_q[2]));
   DFQD1 y_q_reg_1_ (.CP(clk),
	.D(y[1]),
	.Q(y_q[1]));
   DFQD1 y_q_reg_0_ (.CP(clk),
	.D(y[0]),
	.Q(y_q[0]));
   DFQD1 out_reg_5_ (.CP(clk),
	.D(out_wire[5]),
	.Q(out[5]));
   DFQD1 out_reg_4_ (.CP(clk),
	.D(out_wire[4]),
	.Q(out[4]));
   DFQD1 out_reg_3_ (.CP(clk),
	.D(out_wire[3]),
	.Q(out[3]));
   DFQD1 out_reg_2_ (.CP(clk),
	.D(out_wire[2]),
	.Q(out[2]));
   DFQD1 out_reg_1_ (.CP(clk),
	.D(out_wire[1]),
	.Q(out[1]));
   DFQD1 out_reg_0_ (.CP(clk),
	.D(out_wire[0]),
	.Q(out[0]));
endmodule

